version: '2'
services:
    prometheus:
        image: prom/prometheus:0.18.0
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'




# version: '3'

# services:
#   postgres-db:
#     image: postgres:latest
#     container_name: postgres_finman
#     environment:
#       - POSTGRES_PASSWORD=secret
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=finances
#     ports:
#       - '5432:5432'
#     volumes:
#       - database_postgres:/var/lib/postgresql/data
#     networks:
#       - finman

# volumes:
#   database_postgres:                  

# networks:
#   finman:
#     driver: bridge