apiVersion: v1
kind: Service
metadata:
  name: stocktracker
  namespace: tools
spec:
  selector:
    app: stocktracker
  type: NodePort
  ports:
  - name: stocktracker
    protocol: TCP
    port: 2112
    nodePort: 30910